INSERT INTO notes (name, folderId, content)
VALUES 
    ('Clean House', 1, 'Unicorn drinking vinegar butcher selfies literally try-hard, af polaroid everyday carry poke vinyl cliche mumblecore. Try-hard waistcoat hot chicken kitsch slow-carb. Locavore shaman waistcoat bushwick banh mi dreamcatcher brunch hell of direct trade flannel literally vegan.'), 
    ('Wholefoods List', 2, 'Lorem ipsum dolor amet prism venmo woke cardigan. Food truck butcher tbh messenger bag skateboard shoreditch helvetica sartorial farm-to-table before they sold out. Sriracha deep v lo-fi, pug shoreditch brooklyn williamsburg PBR&B. Live-edge bushwick vexillologist activated charcoal humblebrag chambray before they sold out messenger bag narwhal everyday carry meditation mumblecore pabst. '), 
    ('Thinkful Proj', 3, 'Pitchfork master cleanse cronut literally shoreditch helvetica raw denim. La croix green juice trust fund, semiotics hell of wolf etsy. Direct trade distillery 3 wolf moon XOXO four loko kickstarter wayfarers jianbing shoreditch squid vinyl williamsburg subway tile. Shaman pabst microdosing gastropub forage freegan farm-to-table vexillologist tbh hell of trust fund occupy bitters.'), 
    ('Christmas', 4, 'Try-hard meditation tbh post-ironic wayfarers. Meditation cliche post-ironic man braid tacos bespoke flexitarian taiyaki neutra. Mustache palo santo paleo venmo next level master cleanse farm-to-table. Keytar four loko freegan, meditation man braid squid mumblecore. Kitsch shoreditch twee hexagon sustainable retro.'), 
    ('Call Whitney', 5, 'Normcore fashion axe art party artisan, lo-fi pour-over swag locavore. Taiyaki af adaptogen keffiyeh offal gentrify ennui succulents authentic kickstarter. Godard microdosing organic pug chillwave edison bulb pok pok roof party brunch stumptown.'), 
    ('Finishing Thinkful', 6, 'Narwhal enamel pin four loko coloring book cloud bread cronut bespoke butcher dreamcatcher truffaut asymmetrical. Art party dreamcatcher four dollar toast bitters fanny pack.'), 
    ('Mtg Notes', 7, 'Vegan tote bag quinoa, XOXO lo-fi echo park health goth fashion axe subway tile +1 af drinking vinegar jean shorts asymmetrical. Mustache chartreuse fashion axe banh mi vape messenger bag bitters put a bird on it pour-over four dollar toast YOLO whatever.'), 
    ('Party Planning', 8, 'Keffiyeh vinyl fingerstache coloring book. Paleo cred health goth hella schlitz readymade meh air plant. Hot chicken photo booth banjo street art, craft beer messenger bag normcore skateboard neutra fashion axe butcher gastropub affogato slow-carb. '), 
    ('Wolfpack', 9, 'Kogi tbh prism sartorial edison bulb literally cold-pressed. Cornhole celiac asymmetrical keytar ugh green juice. Fashion axe man bun pug gastropub, hot chicken biodiesel ramps chambray copper mug. Wayfarers truffaut chillwave celiac coloring book chambray flexitarian semiotics sartorial pitchfork etsy keytar. La croix cray authentic pitchfork DIY poke locavore distillery semiotics swag raclette 8-bit.'), 
    ('Cams Going Away', 10, 'Hell of bitters vinyl portland fixie, gochujang chartreuse. Tumblr tilde ennui, neutra air plant disrupt occupy shoreditch cold-pressed. Fam cred pinterest, authentic la croix echo park hammock post-ironic raclette chartreuse banh mi. Food truck deep v vexillologist wayfarers keytar YOLO, pitchfork thundercats meggings leggings pok pok. Freegan snackwave cardigan beard health goth, tilde bushwick coloring book venmo.'), 
    ('MKTPLC', 11, 'Cloud bread kogi selvage waistcoat ennui. Taiyaki ugh try-hard disrupt. Authentic irony ramps, post-ironic kombucha biodiesel PBR&B 8-bit squid bicycle rights tousled brooklyn vaporware etsy pug. Letterpress chicharrones hoodie, roof party post-ironic four loko DIY slow-carb beard ramps.'), 
    ('Core Platform', 12, 'Woke pop-up keytar cronut. Poutine chambray neutra beard heirloom. Letterpress thundercats vape heirloom blue bottle paleo.'), 
    ('IFA <> LVG', 13, 'Asymmetrical lomo PBR&B direct trade gastropub distillery echo park 3 wolf moon organic vegan. Prism schlitz readymade art party yuccie. Heirloom semiotics YOLO kinfolk farm-to-table. '), 
    ('Knock Knock', 14, 'Schlitz echo park tote bag chartreuse. Taxidermy williamsburg vape, organic bushwick hella narwhal keffiyeh iPhone hammock intelligentsia franzen normcore hashtag. Kale chips shaman fam humblebrag. '), 
    ('My Deepest Thoughts', 15, 'Kitsch glossier banjo vinyl. Roof party four loko activated charcoal, pork belly iceland quinoa kickstarter kitsch gentrify. Hella synth air plant palo santo, polaroid wayfarers green juice woke post-ironic seitan vinyl thundercats umami shaman. Art party pug godard brooklyn keytar vaporware kitsch sriracha.');